sudo: required
services:
- docker
script: "./script/cibuild"
deploy:
  provider: s3
  access_key_id: AKIAJU7BTFDNZDC2X2VA
  secret_access_key:
    secure: RJm5A1+d6EYwXddeEowNgBFdFuQEIJmv1sowaWxKEbZkIlVqsnW0U6N6aQA3gxIe7QT/5PSsXv19JqAMQLpW2eW/EMXggr5feF0ATotzrAcCq2uu+XrFZ8CRihrJUjlZ4fJkwKU/SxbbBiARrKStODoIEG/R96oIZFZsBOc5xqoMVpOrGds1KMA/iCEnoxYksi6prL2JQKUpa/qDuX9rDKZ6YPZPdXTKzVohTuxmsUdz0QVMCqV7NFbBrfmWDp+WOLZm5i2RgtQCJ770UO5FzYnPvb9rL8dx8xDhqn5ub6iMu4wvrqorTapoKSwEvotsygg6ARfCFTPhmhJE6o7kaw/yc1TM0BxkZjap3iGZzAg3Q5g6ojyv+DaNqR7FkQTVJekD6HkNM6hWyC1PdGc8HprhwoPFRDbmfZ/sUvSXyOVV2vxsLMpwwJ8VgR4g5MH5VmpPF4mHwxxB9opU+XSampaSWZOVvsRyuI2WTUR4GbU2On0GjyG0b3Wg7TwKvzSCw2kCr6ySwEGhRRN2EUJxhfpQzrJ/7alUbvgyYA1bcUxR8DB79MblqGWLFsYu7w0S1VVXM41PDZK6cSWyXspYRIjQlQW6NPW7TVD7I0lcvlVUpFVR+r6KMOZtzKAmCk14Ogi/U1CbDF0qyZixWl7N1VWOWYAwSuNby8IJxfWlgMo=
  bucket: s3.lstoll.net
  local_dir: out
  upload_dir: artifacts/hwrescue
  acl: public_read
  skip_cleanup: true
  on:
    repo: lstoll/hwrescue
    branch: master
