#!/bin/bash

set -e

export DEBIRF_BUILDD=$$TRAVIS_BUILD_DIR/debirf_build
export DEBIRF_OUT=$TRAVIS_BUILD_DIR/out
mkdir -p $DEBIRF_BUILDD
mkdir -p $DEBIRF_OUT

echo "--> Adding all ubuntu repositories"
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
sudo apt-get update > /dev/null

echo "--> Installing dependencies"
sudo apt-get install -qy debirf

echo "--> Building image"
./script/build

echo "--> Copying artifacts to output directory"
cp -v $DEBIRF_BUILDD/*.cgz $DEBIRF_BUILDD/vmlinuz* $DEBIRF_BUILDD/*.iso $DEBIRF_OUT

echo "--> The following files were generated"
ls $DEBIRF_OUT/
