#!/bin/bash

set -e

echo "--> Adding all ubuntu repositories"
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
sudo apt-get update > /dev/null

echo "--> Installing dependencies"
sudo apt-get install -qqy debirf > /dev/null

echo "--> Fetching and nstalling updated debirf"
curl -qLo /tmp/debirf.deb  https://launchpad.net/ubuntu/+archive/primary/+files/debirf_0.35_all.deb
sudo dpkg -i /tmp/debirf.deb

echo "--> Setting up working directories"
export DEBIRF_BUILDD="/tmp/debirf_build"
echo "DEBBIRF_BUILDD is ${DEBIRF_BUILDD}"
mkdir -p $DEBIRF_BUILDD

echo "--> Building image"
./script/build

echo "--> Renaming and copying artifacts to output directory"
mkdir -p out
cp -v $DEBIRF_BUILDD/*.cgz out/initrd.cgz
cp -v $DEBIRF_BUILDD/vmlinuz* out/vmlinuz
cp -v $DEBIRF_BUILDD/*.iso out/image.iso

echo "--> The following files were generated"
ls -l out
