#!/bin/bash

#qemu-system-x86_64 -m 256 -serial stdio -net nic -net user -kernel vmlinuz* -initrd *.cgz

#qemu-system-x86_64 -m 1024 -serial stdio -net nic -net user -kernel vmlinuz* -initrd *.cgz -append "console=ttyS0,115200n8" # console=tty0

#qemu-system-x86_64 -m 1024 -serial stdio -net nic -net user -cdrom *.iso

#-nographic

qemu-system-x86_64 -m 1024 -serial stdio -net nic -net user -kernel vmlinuz* -initrd *.cgz -append "console=ttyS0,115200n8 console=tty0" # console=tty0
