#!/bin/bash

set -e

export DEBIRF_MIRROR=http://localhost:3142/ubuntu
export DEBIRF_BUILDD=$HOME/debirf_build

mkdir -p $DEBIRF_BUILDD

./script/build

cp $DEBIRF_BUILDD/*.cgz .
cp $DEBIRF_BUILDD/vmlinuz* .
cp $DEBIRF_BUILDD/*.iso .
